---
- import_tasks: version-check.yml
  name: "Import version-check.yml"

- include_tasks: remove-ha-all-policy.yml
  name: "Import remove-ha-all-policy.yml"

- import_tasks: config.yml
  name: "Import config.yml"

- import_tasks: feature-flags.yml
  name: "Import feature-flags.yml"

- import_tasks: check-containers.yml
  name: "Import check-containers.yml"
