---
- import_tasks: config.yml
  name: "Import config.yml"

- import_tasks: check-containers.yml
  name: "Import check-containers.yml"

- import_tasks: setup-ovs.yml
  name: "Import setup-ovs.yml"

- name: Flush handlers
  meta: flush_handlers
