---
- import_tasks: config.yml
  name: "Import config.yml"

- import_tasks: check-containers.yml
  name: "Import check-containers.yml"

- import_tasks: bootstrap_service.yml
  name: "Import bootstrap_service.yml"

- name: Flush handlers
  meta: flush_handlers

- import_tasks: update_pools.yml
  name: "Import update_pools.yml"
